#!/bin/sh

set -e

python_renamer(){
    # find some python3.* under /opt/python/bin and rename it to python3.(\1)-real
    find /opt/python/bin -type f -executable -name 'python3.*' -not -name '*-real' -not -name "*-config" | while read -r line; do
        echo "Renaming $line"
        mv "$line" "$(echo "$line" | sed -r 's/python3\.(.*)/python3.\1-real/g')" || (echo "Failed to rename $line" && exit 1)
    done

    # Echo the result
    find /opt/python/bin -type f -executable -name '*-real' | while read -r line; do
        echo "New name: $line"
    done
}

pip_renamer() {
    # find some pip3.* under /opt/python/bin and rename it to pip3.(\1)-real
    find /opt/python/bin -type f -executable -name 'pip3.*' -not -name '*-real' | while read -r line; do
        echo "Renaming $line"
        mv "$line" "$(echo "$line" | sed -r 's/pip3\.(.*)/pip3.\1-real/g')" || (echo "Failed to rename $line" && exit 1)
    done

    # Echo the result
    find /opt/python/bin -type f -executable -name '*-real' | while read -r line; do
        echo "New name: $line"
    done
}

shared_libraries_mover() {
    # Move /opt/shared_libraries to /opt/python/shared_libraries
    mv /opt/shared_libraries /opt/python/shared_libraries
}

main() {
    python_renamer
    pip_renamer
    shared_libraries_mover
}

main
