#!/bin/bash

set -e

# Function to find the real python executable
find_real_python() {
    find "$INSTALL_PREFIX/bin" -type f -executable -name 'python*-real' | head -n 1
}

# Function to find the real pip executable
find_real_pip() {
    find "$INSTALL_PREFIX/bin" -type f -executable -name 'pip*-real' | head -n 1
}

# hack the real pip's shebang to use python-real
hack_real_pip_shebang() {
    local real_pip="$1"
    local real_python="$2"
    sed -i "1s/.*/#!$real_python/" "$real_pip"
}

# Function to set up environment variables
setup_environment() {
    export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    export INSTALL_PREFIX="$SCRIPT_DIR/../"
    
    # Find the REAL_PYTHON and REAL_PIP
    export REAL_PYTHON=$(find_real_python)
    export REAL_PIP=$(find_real_pip)

    # Set PYTHONPATH and backup PYTHONPATH
    export PYTHONPATH_BACKUP=$PYTHONPATH
    
    # Find python version from REAL_PYTHON
    PYTHON_VERSION=$(echo "$REAL_PYTHON" | grep -o -E '[0-9]+\.[0-9]+')
    export PYTHONPATH="$INSTALL_PREFIX/lib/python$PYTHON_VERSION/site-packages"
    PYTHON_VERSION=

    # Set PYTHONHOME to the install prefix
    export PYTHONHOME_BACKUP=$PYTHONHOME
    export PYTHONHOME=$INSTALL_PREFIX

    # hack the real pip's shebang to use python-real
    hack_real_pip_shebang "$REAL_PIP" "$REAL_PYTHON"
}

# Function to invoke the real python and pip
invoke_real_python_pip() {
    cd "$SCRIPT_DIR"
    "$REAL_PYTHON" "$REAL_PIP" "$@"
}

# Function to restore environment variables
restore_environment() {
    export PYTHONHOME=$PYTHONHOME_BACKUP
    export PYTHONPATH=$PYTHONPATH_BACKUP
    cd "$cur_path"
}

# Main script
cur_path=$(pwd)

setup_environment
invoke_real_python_pip "$@"
restore_environment
