name: "release"

on: {
    "push": {
        "branches": ["master"],
    }
}

jobs: {
    release: {
        "runs-on": "ubuntu-latest",
        "strategy": {
            "matrix": {
                "architecture": ["x86_64", "x86"],
                "version": ["3.11"],
            },
        },
        "steps": [
            {
                "name": "Checkout code",
                "uses": "actions/checkout@v3",
            },
            {
                "name": "Build docker image",
                "run": "docker build -t release-${{ github.ref_name }}:${{ matrix.version }}-${{ matrix.architecture }} ./${{ matrix.version }}/${{ matrix.architecture }}/",
            },
            {
                "name": "Save docker image as tar file",
                "run": "docker save release-${{ github.ref_name }}:${{ matrix.version }}-${{ matrix.architecture }} > release-${{ matrix.version }}-${{ matrix.architecture }}.tar",
            },
            {
                "name": "Figure out the /opt/python directory from the tar file",
                "run": "./ci/packing_release_tar.sh release-${{ matrix.version }}-${{ matrix.architecture }}.tar",
            },
            {
                "name": "Release the tar file to release page",
                "uses": "actions/upload-artifact@v3",
                "with": {
                    "name": "release-${{ matrix.version }}-${{ matrix.architecture }}.zip",
                    "path": "build/release-${{ matrix.version }}-${{ matrix.architecture }}.zip",
                },
            },
        ],
    }
}
